#!/usr/bin/env python3
"""Disposable, real three-owner Phase-5 witnessed-workbench fixture.

The fixture generates a PackVault admission projection from a deterministic
Recursive Agent run, then sends those exact generated bytes—not the frozen
fixture corpus—through explicit temporary ClaimLedger and Mnemes owners.
No production roots, ambient credentials, server deployment, or network path
is used.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

RA = Path(__file__).resolve().parents[1]
CLAIM = Path(os.environ.get("CLAIMLEDGER_ROOT", "/home/sikmindz/Coding/ClaimLedger"))
MNEMES = Path(os.environ.get("MNEMES_ROOT", "/home/sikmindz/Coding/mnemes"))
FROZEN_PROJECTION = RA / "fixtures/witnessed-workbench/run-pack-evidence-projection-v1.json"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def require_directory(path: Path, label: str) -> None:
    if not path.is_dir():
        raise SystemExit(f"{label} source root is absent: {path}")


def require_empty_or_absent(path: Path, label: str) -> None:
    if path.exists() and any(path.iterdir()):
        raise SystemExit(f"{label} must be empty and disposable: {path}")
    path.mkdir(parents=True, exist_ok=True)


def command(
    name: str, cmd: list[str], cwd: Path, env: dict[str, str], log_directory: Path
) -> dict[str, Any]:
    completed = subprocess.run(cmd, cwd=cwd, env=env, text=True, capture_output=True)
    log = log_directory / f"{name}.log"
    log.write_text(
        f"$ {' '.join(cmd)}\n# cwd: {cwd}\n# exit: {completed.returncode}\n\n"
        f"[stdout]\n{completed.stdout}\n[stderr]\n{completed.stderr}",
        encoding="utf-8",
    )
    return {
        "case": name,
        "command": cmd,
        "cwd": str(cwd),
        "returncode": completed.returncode,
        "state": "passed" if completed.returncode == 0 else "failed",
        "log_path": str(log),
        "log_sha256": sha256(log),
    }


def detached_receipt(projection: dict[str, Any]) -> dict[str, str]:
    canonical = json.dumps(projection, sort_keys=True, separators=(",", ":")).encode("utf-8")
    verification = projection["verification"]
    return {
        "schema": "RecursiveAgentRunPackVerificationReceiptV1",
        "projection_digest": hashlib.sha256(canonical).hexdigest(),
        "pack_manifest_digest": projection["pack_manifest_digest"],
        "pack_content_digest": projection["pack_content_digest"],
        "verification_receipt_digest": verification["verification_receipt_digest"],
        "outcome": verification["outcome"],
    }


def read_result(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"{label} did not emit valid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise SystemExit(f"{label} result is not a JSON object")
    return value


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True, help="empty disposable fixture root")
    args = parser.parse_args()
    args.root = args.root.resolve()

    require_directory(CLAIM, "ClaimLedger")
    require_directory(MNEMES, "Mnemes")
    require_empty_or_absent(args.root, "fixture root")
    logs = args.root / "logs"
    logs.mkdir()
    projection_path = args.root / "recursive-agent-projection.json"
    verification_receipt_path = args.root / "recursive-agent-verification-receipt.json"
    claim_result_path = args.root / "claim-ledger-result.json"
    mnemes_result_path = args.root / "mnemes-result.json"

    env = os.environ.copy()
    env.update(
        {
            "CARGO_NET_OFFLINE": "true",
            "UV_OFFLINE": "1",
            "PYTHONHASHSEED": "0",
            "RA_PHASE5_TEST_ONLY": "1",
            "RA_PHASE5_PROJECTION_OUT": str(projection_path),
            "MNEMES_PHASE5_PROJECTION": str(projection_path),
            "MNEMES_PHASE5_RECEIPT_OUT": str(mnemes_result_path),
        }
    )
    matrix = [
        command(
            "recursive_agent_real_run_pack_vault_replay",
            [
                "cargo",
                "test",
                "-p",
                "recursive-agent-ledger",
                "--test",
                "run_pack_verify",
                "pack_vault_admits_then_verifies_after_source_is_deleted",
                "--",
                "--exact",
            ],
            RA,
            env,
            logs,
        ),
        command(
            "recursive_agent_generate_verified_admission_projection",
            [
                "cargo",
                "test",
                "-p",
                "recursive-agent-ledger",
                "--test",
                "run_pack_verify",
                "verified_admission_builds_projection_from_pack_evidence_only",
                "--",
                "--exact",
            ],
            RA,
            env,
            logs,
        ),
    ]
    if not projection_path.is_file():
        raise SystemExit("Recursive Agent did not emit its generated admission projection")
    projection = read_result(projection_path, "Recursive Agent projection")
    if sha256(projection_path) == sha256(FROZEN_PROJECTION):
        raise SystemExit("generated projection must not reuse the frozen positive fixture")
    detached = detached_receipt(projection)
    verification_receipt_path.write_text(
        json.dumps(detached, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8"
    )

    matrix.append(
        command(
            "claimledger_import_generated_projection_idempotence_and_tamper_rejection",
            [
                "uv",
                "run",
                "--python",
                "3.11",
                "--extra",
                "dev",
                "python",
                "scripts/witnessed_workbench_fixture.py",
                "--projection",
                str(projection_path),
                "--verification-receipt",
                str(verification_receipt_path),
                "--storage-root",
                str(args.root / "claim-ledger-store"),
                "--negative-root",
                str(args.root / "claim-ledger-negative"),
                "--result",
                str(claim_result_path),
            ],
            CLAIM,
            env,
            logs,
        )
    )
    matrix.append(
        command(
            "mnemes_import_generated_projection_idempotence_and_conflict_rejection",
            [
                "cargo",
                "test",
                "--test",
                "witnessed_workbench_fixture",
                "imports_real_generated_projection_when_fixture_paths_are_explicit",
                "--",
                "--exact",
            ],
            MNEMES,
            env,
            logs,
        )
    )

    claim_result = read_result(claim_result_path, "ClaimLedger")
    mnemes_result = read_result(mnemes_result_path, "Mnemes")
    projection_digest = sha256(projection_path)
    if claim_result.get("projection_sha256") != projection_digest:
        raise SystemExit("ClaimLedger result does not bind the generated projection bytes")
    if mnemes_result.get("projection_sha256") != projection_digest:
        raise SystemExit("Mnemes result does not bind the generated projection bytes")

    passed = all(case["state"] == "passed" for case in matrix)
    receipt = {
        "schema": "witnessed-workbench.phase5.disposable-integration/v1",
        "generated_at": datetime.now(UTC).isoformat(),
        "test_only": True,
        "network": "forbidden: CARGO_NET_OFFLINE=true and UV_OFFLINE=1",
        "source_roots": {
            "recursive_agent": str(RA),
            "claim_ledger": str(CLAIM),
            "mnemes": str(MNEMES),
        },
        "projection": {"path": str(projection_path), "sha256": projection_digest},
        "verification_receipt": {
            "path": str(verification_receipt_path),
            "sha256": sha256(verification_receipt_path),
        },
        "owner_results": {"claim_ledger": claim_result, "mnemes": mnemes_result},
        "matrix": matrix,
        "passed": passed,
        "scope_note": (
            "This is a local, disposable integration fixture. It proves a real PackVault-generated "
            "projection can cross three owner APIs with explicit temporary roots. It does not prove "
            "the separate crash-recovery, snapshot-restore, final retrieval-projection, deployment, "
            "or live-Hermes-session gates in the witnessed-workbench roadmap."
        ),
    }
    receipt_path = args.root / "phase5-conformance.json"
    receipt_path.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "receipt": str(receipt_path),
                "receipt_sha256": sha256(receipt_path),
                "passed": passed,
            }
        )
    )
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
